version: "4.3"

services:
    meetrip_fe-app:
        build:
            context: "."
        container_name: meetrip_fe-app
        ports:
            - 8089:8081
        networks:
            backend:
                aliases:
                    - app

networks:
    backend:
        name: meetrip_fe-network